name: CI & Deploy

on:
  push:
    branches: [ master, develop ]

jobs:
  test:
    name: Test (Jest + Migration)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd "pg_isready -U postgres -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: testdb

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: matching-agent
        run: npm ci

      - name: Run SQL Migrations (Test-DB)
        working-directory: matching-agent
        run: |
          psql -c "\dt" || echo "DB empty, applying migrations"
          psql -f base44/migrations/001_create_embeddings_table.sql

      - name: Run Jest Tests
        working-directory: matching-agent
        run: npm test

  deploy:
    name: Deploy to Prod
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Apply migrations in Base44
        working-directory: matching-agent
        env:
          BASE44_API_URL: ${{ secrets.BASE44_API_URL }}
          BASE44_API_KEY: ${{ secrets.BASE44_API_KEY }}
        run: |
          for f in base44/migrations/*.sql; do
            echo "Applying $f to Base44"
            curl -X POST "$BASE44_API_URL/migrations/apply" \
              -H "Authorization: Bearer $BASE44_API_KEY" \
              -H "Content-Type: text/sql" \
              --data-binary @"$f"
          done

      - name: Import n8n Workflows
        working-directory: matching-agent
        env:
          N8N_URL:     ${{ secrets.N8N_URL }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
        run: |
          for f in n8n/*.json; do
            echo "Importing $f into n8n"
            curl -X POST "$N8N_URL/rest/workflows/import" \
              -H "Authorization: Bearer $N8N_API_KEY" \
              -H "Content-Type: application/json" \
              --data @"$f"
          done
