name: CI & Deploy

on:
  push:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # ...

    env:
      # ...

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run SQL Migrations (Test-DB)
        run: |
          psql -c "\dt" || echo "DB empty"
          psql -f base44/migrations/001_create_embeddings_table.sql

      - name: Run Jest Tests
        run: npm test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Apply migrations in Base44
        env:
          BASE44_API_URL: ${{ secrets.BASE44_API_URL }}
          BASE44_API_KEY: ${{ secrets.BASE44_API_KEY }}
        run: |
          for f in base44/migrations/*.sql; do
            curl -X POST "$BASE44_API_URL/migrations/apply" \
              -H "Authorization: Bearer $BASE44_API_KEY" \
              --data-binary @"$f"
          done

      - name: Import n8n Workflows
        env:
          N8N_URL:     ${{ secrets.N8N_URL }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
        run: |
          for f in n8n/*.json; do
            curl -X POST "$N8N_URL/rest/workflows/import" \
              -H "Authorization: Bearer $N8N_API_KEY" \
              --data @"$f"
          done
